<template>
  <div class="mt-4">
      <div class="container">
          <div class="if-condition container-fluid d-flex flex-row ps-0">
              <span class="text-center me-2 condition rounded">IF</span>
              <select class="form-select form-select-sm me-2 if-select" v-model="if_condition">
                <option value="ALL">ALL</option>
                <option value="ANY">ANY</option>
                <option value="NONE">NONE</option>
              </select>
              <span>of these filters match</span>
          </div>
          <div class="mt-3 ps-3 pt-3 pb-3 border">
            <new-rule v-for="(item, index) in rules"
                      :key="JSON.stringify(item.id)" v-on:remove-rule="removeRule(index)"
                      :data="item" :index="index" v-on:data-changed="dataChanged"
                      class="mb-2"/>
            <div class="mt-2 add-rule-div">
              <button class="btn add-rule-btn" v-on:click="addRule">+</button>
            </div>
          </div>
          <div class="if-condition container-fluid d-flex flex-row ps-0 mt-3">
              <span class="text-center me-2 condition rounded">THEN</span>
              <select class="form-select form-select-sm me-2 then-select" v-model="then_condition">
                <option value="RETURN">RETURN</option>
                <option value="SAVE">SAVE TO</option>
                <option value="NOTIFICATION">SEND NOTIFICATION TO</option>
              </select>
              <select v-if="then_condition === 'SAVE'" class="form-select form-select-sm me-2 then-select" v-model="save_condition">
                <option value="DATABASE">DATABASE</option>
                <option value="CSV">CSV</option>
              </select>
              <select v-if="then_condition === 'NOTIFICATION'" class="form-select form-select-sm me-2 then-select" v-model="noti_condition">
                <option value="EMAIL">EMAIL</option>
                <option value="SMS">SMS</option>
                <option value="WEBHOOK">WEBHOOK</option>
              </select>
          </div>
          <div v-if="then_condition === 'SAVE'" class="mt-3 ps-3 pt-3 pb-3 border">
            <save-to-database v-if="save_condition === 'DATABASE'"/>
          </div>
      </div>
  </div>
</template>

<script>
import Rule from '@/components/Rule'
import SaveToDatabase from "@/components/SaveToDatabase";

export default {
  name: "NewTask",
  components: {
    'new-rule': Rule,
    'save-to-database': SaveToDatabase
  },
  data: function () {
    return {
      if_condition: 'ALL',
      then_condition: 'RETURN',
      save_condition: 'DATABASE',
      noti_condition: 'EMAIL',
      rules: []
    }
  },
  beforeMount() {
    // Add initial rule
    this.addRule()
  },
  methods: {
      dataChanged(data) {
        /*
        * This rule is triggered by the child component
        * when the rule data is updated/changed and its
        * job is to update the data object in the parent
        */
        const rules = this.rules;
        const index = data.index;
        delete data['index'];
        rules.splice(index, 1, data)
        this.rules = rules;
      },
      removeRule(index) {
        /*
        * This rule is triggered by the child component
        * and its job is to remove the rule from the data
        * object in the parent using its index
        */
        const rules = this.rules;
        rules.splice(index, 1)
        this.rules = rules
      },
      addRule() {
        /*
        * This rule is triggered by the button in the parent
        * and when ran it adds a new rule to the data object
        *
        * Because we need an id for the v-bind:key we need to
        * generate a new id and for that we simply add 1 to the
        * last id saved in the array. When saving to the database
        * this id will be renewed with one generated by the database
        */
        let default_id
        if (this.rules.length > 0) {
          default_id = this.rules[this.rules.length - 1].id + 1
        } else {
          default_id = 1
        }
        const new_rule = {
          id: default_id,
          type_input_text: null,
          type_input_show: null,
          rule_input_text: null,
          rule_input_show: null,
        }
        this.rules.push(new_rule)
      }
    }
  }
</script>

<!-- Global CSS -->
<style>
  .form-select-sm {
    padding-top: 0;
    padding-bottom: 0;
    width: 200px;
  }
</style>

<style scoped>
  .if-condition > .condition {
      width: 80px;
      background-color: #212121;
      color: white;
      padding-top: 1px;
  }
  .if-condition > .if-select {
    width: 90px;
  }
  .if-condition > .then-select {
    width: 210px;
  }
  .add-rule-div {
    text-align: initial;
  }
  .add-rule-div > .add-rule-btn {
    background: #212121;
    color: white;
    width: 80px;
  }
</style>